services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      SERVICES: dynamodb
      DEBUG: 1
    volumes: 
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data: {}
